// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKPzjWNy93zXhiN1s2m7JBFZpuBRR8xzw',
    appId: '1:714593542275:web:217e98d9ca7fd216783bb6',
    messagingSenderId: '714593542275',
    projectId: 'chat-app-ac0db',
    authDomain: 'chat-app-ac0db.firebaseapp.com',
    storageBucket: 'chat-app-ac0db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTa0eHjMZ5jLaWRRB7Ruo8N9SUba4XUbE',
    appId: '1:714593542275:android:684565eeb8b57b6b783bb6',
    messagingSenderId: '714593542275',
    projectId: 'chat-app-ac0db',
    storageBucket: 'chat-app-ac0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqVCP-75JA2brHd9G3X-0X77DZ9oM8ug4',
    appId: '1:714593542275:ios:4ab6d9ed3f5e3513783bb6',
    messagingSenderId: '714593542275',
    projectId: 'chat-app-ac0db',
    storageBucket: 'chat-app-ac0db.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqVCP-75JA2brHd9G3X-0X77DZ9oM8ug4',
    appId: '1:714593542275:ios:4ab6d9ed3f5e3513783bb6',
    messagingSenderId: '714593542275',
    projectId: 'chat-app-ac0db',
    storageBucket: 'chat-app-ac0db.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKPzjWNy93zXhiN1s2m7JBFZpuBRR8xzw',
    appId: '1:714593542275:web:3bce59dfb1fa5367783bb6',
    messagingSenderId: '714593542275',
    projectId: 'chat-app-ac0db',
    authDomain: 'chat-app-ac0db.firebaseapp.com',
    storageBucket: 'chat-app-ac0db.appspot.com',
  );
}
